// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product_Display.Data;

#nullable disable

namespace Product_Display.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250516053306_AddForexRate")]
    partial class AddForexRate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product_Display.Models.FGNBond", b =>
                {
                    b.Property<string>("ISIN")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<double>("Coupon")
                        .HasColumnType("float");

                    b.Property<DateTime>("Maturity")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Security")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("YearsToMaturity")
                        .HasColumnType("float");

                    b.Property<double>("YieldToMaturity")
                        .HasColumnType("float");

                    b.HasKey("ISIN");

                    b.ToTable("FGNBonds");
                });

            modelBuilder.Entity("Product_Display.Models.ForexRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUpwardTrend")
                        .HasColumnType("bit");

                    b.Property<decimal>("SellRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ForexRates");
                });

            modelBuilder.Entity("Product_Display.Models.TreasuryBP", b =>
                {
                    b.Property<string>("SecurityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Maturity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenorDays")
                        .HasColumnType("int");

                    b.HasKey("SecurityId");

                    b.ToTable("Treasuries");
                });
#pragma warning restore 612, 618
        }
    }
}
