// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product_Display.Data;

#nullable disable

namespace Product_Display.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250506090026_AddTreasuryBP")]
    partial class AddTreasuryBP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product_Display.Models.TreasuryBP", b =>
                {
                    b.Property<string>("SecurityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Maturity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenorDays")
                        .HasColumnType("int");

                    b.HasKey("SecurityId");

                    b.ToTable("Treasuries");
                });
#pragma warning restore 612, 618
        }
    }
}
